apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: admin
  name: admin
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: admin
    spec:
      containers:
      - name: admin
        image: us.gcr.io/ponzu-example/admin:v1
        command: ["bash"]
        args: ["/go/src/project/start_admin.sh", "start"]
        resources: {}
        volumeMounts:
        - mountPath: /go/src/project
          name: admin-claim0
      restartPolicy: Always
      volumes:
      - name: admin-claim0
        persistentVolumeClaim:
          claimName: admin-claim0
status: {}
