apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: web
  name: web
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - name: web
        image: us.gcr.io/ponzu-example/web:v1
        ports:
        - containerPort: 3000
        resources: {}
        volumeMounts:
        # this name must match the volumes.name below
        - name: web-disk
          mountPath: /public
      restartPolicy: Always
      volumes:
      - name: web-disk
        gcePersistentDisk:
          # this disk must already exist
          pdName: web-pd0
          fsType: ext4
status: {}
